image: maven:3-jdk-7

stages:
- build
- test
- deploy

before_script:
  - mkdir target

build:
  stage: build
  script: 
  - echo "==============================="
  - echo "Start building war package..."
  - echo "==============================="
  - mvn package -U
  - echo "==============================="
  - echo "Finish building war package."
  - echo "==============================="
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - target/*.war
    when: on_success
    expire_in: 1 week
