image: maven:3-jdk-7

stages:
- build
- test
- deploy

build:
  stage: build
  script: 
  - echo "==============================="
  - echo "Start building war package..."
  - echo "==============================="
  - mvn install -B
  - echo "==============================="
  - echo "Finish building war package."
  - echo "==============================="

deploy_staging:
  stage: build
  script:
    - echo "Deployinf to staging server build"
  environment:
    name: build
    url: https://build.javsterisk.com
  only:
  - master
