image: maven:3-jdk-7

stages:
- build
- test
- deploy

build:
  stage: build
  script: 
  - echo "==============================="
  - echo "Start building war package..."
  - echo "==============================="
  - mvn package -U
  - echo "==============================="
  - echo "Finish building war package."
  - echo "==============================="
