image: maven:3-jdk-7

stages:
- build
- test
- deploy

before_script:
  - mkdir target

build:
  stage: build
  script: 
  - echo "==============================="
  - echo "Start building war package..."
  - echo "==============================="
  - mvn package -U
  - echo "==============================="
  - echo "Finish building war package."
  - echo "==============================="
  artifacts:
    paths:
      - target/*.war
    when: on_success
    expire_in: 1 week

deploy_staging:
  stage: build
  script:
    - echo "Deploying to staging server build"
  environment:
    name: build
    url: https://build.javsterisk.com
  only:
  - master
