package com.web.javsterisk.entity;

// Generated 09-02-2014 11:19:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Cdr generated by hbm2java
 */
@Entity
@Table(name = "cdr")
public class Cdr implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
//	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@NotNull
	@Temporal(TemporalType.TIMESTAMP)		
//	@Column(name = "calldate", nullable = false, length = 19)
	private Date calldate;
	
	@NotNull
	@Size(max = 80)
//	@Column(name = "clid", nullable = false, length = 80)
	private String clid;

	@NotNull
	@Size(max = 80)
//	@Column(name = "src", nullable = false, length = 80)
	private String src;

	@NotNull
	@Size(max = 80)
//	@Column(name = "dst", nullable = false, length = 80)
	private String dst;

	@NotNull
	@Size(max = 80)
//	@Column(name = "dcontext", nullable = false, length = 80)
	private String dcontext;

	@NotNull
	@Size(max = 200)
//	@Column(name = "lastapp", nullable = false, length = 200)
	private String lastapp;
	
//	@NotNull
	@Size(max = 200)
//	@Column(name = "lastdata", nullable = false, length = 200)		
	private String lastdata;
		
	@Column(name = "duration", precision = 12, scale = 0)	
	private Float duration;
	
	@Transient
	private String durationTime;

	@Column(name = "billsec", precision = 12, scale = 0)
	private Float billsec;
	
	@Size(max = 10)
//	@Column(name = "disposition", length = 10)
	private String disposition;

	@Size(max = 50)
//	@Column(name = "channel", length = 50)
	private String channel;

	@Size(max = 50)
//	@Column(name = "dstchannel", length = 50)
	private String dstchannel;
	
	@Size(max = 50)
//	@Column(name = "amaflags", length = 50)
	private String amaflags;

	@Size(max = 20)
//	@Column(name = "accountcode", length = 20)
	private String accountcode;

	@NotNull
	@Size(max = 32)
//	@Column(name = "uniqueid", nullable = false, length = 32)
	private String uniqueid;
	
	@Column(name = "userfield", precision = 12, scale = 0)
	private Float userfield;

	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "answer", nullable = false, length = 19)
	private Date answer;

	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "end", nullable = false, length = 19)
	private Date end;
	
	@Transient
	private String recorder;

	public Cdr() {
	}

	public Cdr(Date calldate, String clid, String src, String dst,
			String dcontext, String lastapp, String lastdata, String uniqueid,
			Date answer, Date end) {
		this.calldate = calldate;
		this.clid = clid;
		this.src = src;
		this.dst = dst;
		this.dcontext = dcontext;
		this.lastapp = lastapp;
		this.lastdata = lastdata;
		this.uniqueid = uniqueid;
		this.answer = answer;
		this.end = end;
	}

	public Cdr(Date calldate, String clid, String src, String dst,
			String dcontext, String lastapp, String lastdata, Float duration,
			Float billsec, String disposition, String channel,
			String dstchannel, String amaflags, String accountcode,
			String uniqueid, Float userfield, Date answer, Date end) {
		this.calldate = calldate;
		this.clid = clid;
		this.src = src;
		this.dst = dst;
		this.dcontext = dcontext;
		this.lastapp = lastapp;
		this.lastdata = lastdata;
		this.duration = duration;
		this.billsec = billsec;
		this.disposition = disposition;
		this.channel = channel;
		this.dstchannel = dstchannel;
		this.amaflags = amaflags;
		this.accountcode = accountcode;
		this.uniqueid = uniqueid;
		this.userfield = userfield;
		this.answer = answer;
		this.end = end;
	}
	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public Date getCalldate() {
		return this.calldate;
	}

	public void setCalldate(Date calldate) {
		this.calldate = calldate;
	}
	
	public String getClid() {
		return this.clid;
	}

	public void setClid(String clid) {
		this.clid = clid;
	}
	
	public String getSrc() {
		return this.src;
	}

	public void setSrc(String src) {
		this.src = src;
	}
	
	public String getDst() {
		return this.dst;
	}

	public void setDst(String dst) {
		this.dst = dst;
	}
	
	public String getDcontext() {
		return this.dcontext;
	}

	public void setDcontext(String dcontext) {
		this.dcontext = dcontext;
	}
	
	public String getLastapp() {
		return this.lastapp;
	}

	public void setLastapp(String lastapp) {
		this.lastapp = lastapp;
	}
	
	public String getLastdata() {
		return this.lastdata;
	}

	public void setLastdata(String lastdata) {
		this.lastdata = lastdata;
	}
	
	public Float getDuration() {
		return this.duration;
	}

	public void setDuration(Float duration) {
		this.duration = duration;
	}
	
	public String getDurationTime() {
		return durationTime;
	}

	public void setDurationTime(String durationTime) {
		this.durationTime = durationTime;
	}

	public Float getBillsec() {
		return this.billsec;
	}

	public void setBillsec(Float billsec) {
		this.billsec = billsec;
	}
	
	public String getDisposition() {
		return this.disposition;
	}

	public void setDisposition(String disposition) {
		this.disposition = disposition;
	}
	
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}
	
	public String getDstchannel() {
		return this.dstchannel;
	}

	public void setDstchannel(String dstchannel) {
		this.dstchannel = dstchannel;
	}
	
	public String getAmaflags() {
		return this.amaflags;
	}

	public void setAmaflags(String amaflags) {
		this.amaflags = amaflags;
	}
	
	public String getAccountcode() {
		return this.accountcode;
	}

	public void setAccountcode(String accountcode) {
		this.accountcode = accountcode;
	}

	
	public String getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}
	
	public Float getUserfield() {
		return this.userfield;
	}

	public void setUserfield(Float userfield) {
		this.userfield = userfield;
	}
	
	public Date getAnswer() {
		return this.answer;
	}

	public void setAnswer(Date answer) {
		this.answer = answer;
	}
	
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public String getRecorder() {
		return recorder;
	}

	public void setRecorder(String recorder) {
		this.recorder = recorder;
	}

}
