package com.web.javsterisk.entity;

// Generated 07-03-2014 12:13:46 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * SipBuddies generated by hbm2java
 */
@Entity
@Table(name = "sip_buddies", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SipBuddies implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@NotNull
	@Size(max = 80)
	@Column(name = "name", unique = true, nullable = false, length = 80)
	private String name;

	@Size(max = 80)
	@Column(name = "callerid", length = 80)
	private String callerid = null;
	
	@NotNull
	@Size(max = 80)
	@Column(name = "defaultuser", nullable = false, length = 80)	
	private String defaultuser;

	@Size(max = 80)
	@Column(name = "regexten", length = 80)
	private String regexten = null;

	@Size(max = 80)
	@Column(name = "secret", length = 80)
	private String secret = null;
	
	@Size(max = 50)
	@Column(name = "mailbox", length = 50)
	private String mailbox = null;
	
	@Size(max = 20)
	@Column(name = "accountcode", length = 20)	
	private String accountcode = null;
	
	@NotNull
	@Size(max = 80)
	@Column(name = "context", nullable = false, length = 80)	
	private String context = null;//"from-sip";
	
	@Size(max = 7)
	@Column(name = "amaflags", length = 7)	
	private String amaflags = null;

	@Size(max = 10)
	@Column(name = "callgroup", length = 10)
	private String callgroup = null;

	@Size(max = 3)
	@Column(name = "canreinvite", length = 3)
	private String canreinvite = "yes";
	
	@Size(max = 15)
	@Column(name = "defaultip", length = 15)
	private String defaultip = null;
	
	@Size(max = 7)
	@Column(name = "dtmfmode", length = 7)
	private String dtmfmode = null;
	
	@Size(max = 80)
	@Column(name = "fromuser", length = 80)
	private String fromuser = null;
	
	@Size(max = 80)
	@Column(name = "fromdomain", length = 80)
	private String fromdomain = null;
	
	@Size(max = 80)
	@Column(name = "fullcontact", length = 80)
	private String fullcontact = null;
	
	@NotNull
	@Size(max = 31)
	@Column(name = "host", nullable = false, length = 31)
	private String host;
	
	@Size(max = 4)
	@Column(name = "insecure", length = 4)
	private String insecure = null;
	
	@Size(max = 2)
	@Column(name = "language", length = 2)
	private String language = null;
	
	@Size(max = 80)
	@Column(name = "md5secret", length = 80)
	private String md5secret = null;
	
	@NotNull
	@Size(max = 5)
	@Column(name = "nat", nullable = false, length = 5)
	private String nat = "yes";
	
	@Size(max = 95)
	@Column(name = "deny", length = 95)
	private String deny = null;
	
	@Size(max = 95)
	@Column(name = "permit", length = 95)
	private String permit = null;
	
	@Size(max = 95)
	@Column(name = "mask", length = 95)
	private String mask = null;
	
	@Size(max = 10)
	@Column(name = "pickupgroup", length = 10)
	private String pickupgroup = null;
		
	@Size(max = 5)
	@Column(name = "port", length = 5)
	private String port;
	
	@Size(max = 3)
	@Column(name = "qualify", length = 3)
	private String qualify = "yes";
	
	@Size(max = 1)
	@Column(name = "restrictcid", length = 1)
	private String restrictcid = null;
	
	@Size(max = 3)
	@Column(name = "rtptimeout", length = 3)
	private String rtptimeout = null;
	
	@Size(max = 3)
	@Column(name = "rtpholdtimeout", length = 3)
	private String rtpholdtimeout = null;
	
	@NotNull
	@Size(max = 6)
	@Column(name = "type", nullable = false, length = 6)
	private String type = "friend";
	
	@Size(max = 100)
	@Column(name = "disallow", length = 100)
	private String disallow = null;
	
	@Size(max = 100)
	@Column(name = "allow", length = 100)
	private String allow = "g729;ilbc;gsm;ulaw;alaw";
	
	@Size(max = 100)
	@Column(name = "musiconhold", length = 100)
	private String musiconhold = null;

	@NotNull
	@Column(name = "regseconds", nullable = false)
	private int regseconds = 0;
	
	@Size(max = 45)
	@Column(name = "ipaddr", length = 45)
	private String ipaddr;
	
	@Size(max = 3)
	@Column(name = "cancallforward", length = 3)	
	private String cancallforward = "yes";

	@NotNull
	@Column(name = "lastms", nullable = false)
	private int lastms;

	@Column(name = "useragent")
	private String useragent = null;
	
	@Size(max = 100)
	@Column(name = "regserver", length = 100)
	private String regserver = null;
	
	public SipBuddies() {
	}

	public SipBuddies(String name, String defaultuser, String host, String nat,
			String port, String type, int regseconds, String ipaddr, int lastms) {
		this.name = name;
		this.defaultuser = defaultuser;
		this.host = host;
		this.nat = nat;
		this.port = port;
		this.type = type;
		this.regseconds = regseconds;
		this.ipaddr = ipaddr;
		this.lastms = lastms;
	}

	public SipBuddies(String name, String callerid, String defaultuser,
			String regexten, String secret, String mailbox, String accountcode,
			String context, String amaflags, String callgroup,
			String canreinvite, String defaultip, String dtmfmode,
			String fromuser, String fromdomain, String fullcontact,
			String host, String insecure, String language, String md5secret,
			String nat, String deny, String permit, String mask,
			String pickupgroup, String port, String qualify,
			String restrictcid, String rtptimeout, String rtpholdtimeout,
			String type, String disallow, String allow, String musiconhold,
			int regseconds, String ipaddr, String cancallforward, int lastms,
			String useragent, String regserver) {
		this.name = name;
		this.callerid = callerid;
		this.defaultuser = defaultuser;
		this.regexten = regexten;
		this.secret = secret;
		this.mailbox = mailbox;
		this.accountcode = accountcode;
		this.context = context;
		this.amaflags = amaflags;
		this.callgroup = callgroup;
		this.canreinvite = canreinvite;
		this.defaultip = defaultip;
		this.dtmfmode = dtmfmode;
		this.fromuser = fromuser;
		this.fromdomain = fromdomain;
		this.fullcontact = fullcontact;
		this.host = host;
		this.insecure = insecure;
		this.language = language;
		this.md5secret = md5secret;
		this.nat = nat;
		this.deny = deny;
		this.permit = permit;
		this.mask = mask;
		this.pickupgroup = pickupgroup;
		this.port = port;
		this.qualify = qualify;
		this.restrictcid = restrictcid;
		this.rtptimeout = rtptimeout;
		this.rtpholdtimeout = rtpholdtimeout;
		this.type = type;
		this.disallow = disallow;
		this.allow = allow;
		this.musiconhold = musiconhold;
		this.regseconds = regseconds;
		this.ipaddr = ipaddr;
		this.cancallforward = cancallforward;
		this.lastms = lastms;
		this.useragent = useragent;
		this.regserver = regserver;
	}
	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String getCallerid() {
		return this.callerid;
	}

	public void setCallerid(String callerid) {
		this.callerid = callerid;
	}
	
	public String getDefaultuser() {
		return this.defaultuser;
	}

	public void setDefaultuser(String defaultuser) {
		this.defaultuser = defaultuser;
	}
	
	public String getRegexten() {
		return this.regexten;
	}

	public void setRegexten(String regexten) {
		this.regexten = regexten;
	}
	
	public String getSecret() {
		return this.secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}
	
	public String getMailbox() {
		return this.mailbox;
	}

	public void setMailbox(String mailbox) {
		this.mailbox = mailbox;
	}
	
	public String getAccountcode() {
		return this.accountcode;
	}

	public void setAccountcode(String accountcode) {
		this.accountcode = accountcode;
	}
	
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}
	
	public String getAmaflags() {
		return this.amaflags;
	}

	public void setAmaflags(String amaflags) {
		this.amaflags = amaflags;
	}
	
	public String getCallgroup() {
		return this.callgroup;
	}

	public void setCallgroup(String callgroup) {
		this.callgroup = callgroup;
	}
	
	public String getCanreinvite() {
		return this.canreinvite;
	}

	public void setCanreinvite(String canreinvite) {
		this.canreinvite = canreinvite;
	}
	
	public String getDefaultip() {
		return this.defaultip;
	}

	public void setDefaultip(String defaultip) {
		this.defaultip = defaultip;
	}
	
	public String getDtmfmode() {
		return this.dtmfmode;
	}

	public void setDtmfmode(String dtmfmode) {
		this.dtmfmode = dtmfmode;
	}
	
	public String getFromuser() {
		return this.fromuser;
	}

	public void setFromuser(String fromuser) {
		this.fromuser = fromuser;
	}
	
	public String getFromdomain() {
		return this.fromdomain;
	}

	public void setFromdomain(String fromdomain) {
		this.fromdomain = fromdomain;
	}
	
	public String getFullcontact() {
		return this.fullcontact;
	}

	public void setFullcontact(String fullcontact) {
		this.fullcontact = fullcontact;
	}
	
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}
	
	public String getInsecure() {
		return this.insecure;
	}

	public void setInsecure(String insecure) {
		this.insecure = insecure;
	}
	
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}
	
	public String getMd5secret() {
		return this.md5secret;
	}

	public void setMd5secret(String md5secret) {
		this.md5secret = md5secret;
	}
	
	public String getNat() {
		return this.nat;
	}

	public void setNat(String nat) {
		this.nat = nat;
	}
	
	public String getDeny() {
		return this.deny;
	}

	public void setDeny(String deny) {
		this.deny = deny;
	}
	
	public String getPermit() {
		return this.permit;
	}

	public void setPermit(String permit) {
		this.permit = permit;
	}
	
	public String getMask() {
		return this.mask;
	}

	public void setMask(String mask) {
		this.mask = mask;
	}
	
	public String getPickupgroup() {
		return this.pickupgroup;
	}

	public void setPickupgroup(String pickupgroup) {
		this.pickupgroup = pickupgroup;
	}
	
	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}
	
	public String getQualify() {
		return this.qualify;
	}

	public void setQualify(String qualify) {
		this.qualify = qualify;
	}
	
	public String getRestrictcid() {
		return this.restrictcid;
	}

	public void setRestrictcid(String restrictcid) {
		this.restrictcid = restrictcid;
	}
	
	public String getRtptimeout() {
		return this.rtptimeout;
	}

	public void setRtptimeout(String rtptimeout) {
		this.rtptimeout = rtptimeout;
	}
	
	public String getRtpholdtimeout() {
		return this.rtpholdtimeout;
	}

	public void setRtpholdtimeout(String rtpholdtimeout) {
		this.rtpholdtimeout = rtpholdtimeout;
	}
	
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	public String getDisallow() {
		return this.disallow;
	}

	public void setDisallow(String disallow) {
		this.disallow = disallow;
	}
	
	public String getAllow() {
		return this.allow;
	}

	public void setAllow(String allow) {
		this.allow = allow;
	}
	
	public String getMusiconhold() {
		return this.musiconhold;
	}

	public void setMusiconhold(String musiconhold) {
		this.musiconhold = musiconhold;
	}
	
	public int getRegseconds() {
		return this.regseconds;
	}

	public void setRegseconds(int regseconds) {
		this.regseconds = regseconds;
	}
	
	public String getIpaddr() {
		return this.ipaddr;
	}

	public void setIpaddr(String ipaddr) {
		this.ipaddr = ipaddr;
	}
	
	public String getCancallforward() {
		return this.cancallforward;
	}

	public void setCancallforward(String cancallforward) {
		this.cancallforward = cancallforward;
	}
	
	public int getLastms() {
		return this.lastms;
	}

	public void setLastms(int lastms) {
		this.lastms = lastms;
	}
	
	public String getUseragent() {
		return this.useragent;
	}

	public void setUseragent(String useragent) {
		this.useragent = useragent;
	}
	
	public String getRegserver() {
		return this.regserver;
	}

	public void setRegserver(String regserver) {
		this.regserver = regserver;
	}


	@Override
	public int hashCode() {
		return (id != null)
		        ? (this.getClass().hashCode() + id.hashCode())
		        : super.hashCode();
	}
	@Override
	public boolean equals(Object other) {
	    return (other instanceof SipBuddies) && (id != null)
	        ? id.equals(((SipBuddies) other).id)
	        : (other == this);
	}

	@Override
	public String toString() {
		return "SipBuddies [id=" + id + ", name=" + name + ", callerid="
				+ callerid + ", defaultuser=" + defaultuser + ", regexten="
				+ regexten + ", secret=" + secret + ", mailbox=" + mailbox
				+ ", accountcode=" + accountcode + ", context=" + context
				+ ", amaflags=" + amaflags + ", callgroup=" + callgroup
				+ ", canreinvite=" + canreinvite + ", defaultip=" + defaultip
				+ ", dtmfmode=" + dtmfmode + ", fromuser=" + fromuser
				+ ", fromdomain=" + fromdomain + ", fullcontact=" + fullcontact
				+ ", host=" + host + ", insecure=" + insecure + ", language="
				+ language + ", md5secret=" + md5secret + ", nat=" + nat
				+ ", deny=" + deny + ", permit=" + permit + ", mask=" + mask
				+ ", pickupgroup=" + pickupgroup + ", port=" + port
				+ ", qualify=" + qualify + ", restrictcid=" + restrictcid
				+ ", rtptimeout=" + rtptimeout + ", rtpholdtimeout="
				+ rtpholdtimeout + ", type=" + type + ", disallow=" + disallow
				+ ", allow=" + allow + ", musiconhold=" + musiconhold
				+ ", regseconds=" + regseconds + ", ipaddr=" + ipaddr
				+ ", cancallforward=" + cancallforward + ", lastms=" + lastms
				+ ", useragent=" + useragent + ", regserver=" + regserver + "]";
	}
	
	
}
